local M = {}

---Updates each node of the tree with the ID generated by the ID generator.
---@param tree editree.Tree
---@param id_generator editree.IdGenerator
M.add_ids = function(tree, id_generator)
	local i = 2
	tree:for_each(function(node)
		if not node:is_root() then
			local id = id_generator.get_id()
			node.id = id
			i = i + 1
		end
	end)
end

return M
